### ISSUE TITLE
CPL_LOG

### ISSUE THREAD

**Issue by schneidermichal** [geonef/php5-gdal#10]
Hi,

I'm wondering if you are using CPL_LOG config option. I tried to set up the option, but without success :-( I'm trying something like this: CPLSetConfigOption("CPL_LOG", "D:\temp\gdal.log"). Am I missing something?

Thank you for any advice!

**Comment by geonef** [comment]
Hi,

No, I think I don't use CPL_LOG through php5-gdal. I remember I use it through MapServer but it's not set through php-gdal, so I can't help you.

Maybe there's a default logfile to check, otherwise a step-by-step debugging (gdb...) on the PHP or CPL function. If you haven't fixed your problem already.

Good luck!

**Comment by schneidermichal** [comment]
Hi,

thanks for reply. I don't know why, but it is working now :-)
